### ISSUE TITLE
Pull in sample field entries from variables.yaml file

### ISSUE THREAD

**Issue by sinak** [EFForg/congress-forms-test#15]
The bookmarklet grabs the field entries from this file, would be great if the test tool did the same:

https://github.com/unitedstates/contact-congress/blob/master/support/variables.yaml

**Comment by sinak** [comment]
This is also breaking http://efforg.github.io/congress-forms-test/?bioguide_id=G000289

The default phone number should be of the format 999-999-9999, but the example value used is (999) 999-9999. That is the $PHONE_BRACKETS variable, which is now distinct (as of yesterday). This should be fixed ASAP, as it means any of the YAML files we've generated so far may be broken.

**Comment by sinak** [comment]
There is also a new $ADDRESS_STATE_FULL variable in the YAML file above that needs to be added.

**Comment by thomasdavis** [comment]
Values are pulled from the example yaml file now, I believe this should fix all these issues.
