### ISSUE TITLE
Contact form URL should be pulled in from the YAML

### ISSUE THREAD

**Issue by sinak** [EFForg/congress-forms-test#17]
For example, this one is wrong: http://efforg.github.io/congress-forms-test/?bioguide_id=U000031

Should be pulled in from relevant YAML file rather than from global list.

**Comment by thomasdavis** [comment]
So it was actually being pulled from https://congress.api.sunlightfoundation.com/legislators

But I guess theirs is out of date. Updating it to pull from YAML

**Comment by thomasdavis** [comment]
Yeppppp
