### ISSUE TITLE
SSL Mixed content error

### ISSUE THREAD

**Issue by timdavila** [EFForg/congress-forms-test#26]
I use HTTPS Everywhere. Now that gihub.io enabled SSL, I get a mixed content warning and a blank page. Even after ignoring the warning on https, I get a blue progress bar and the content refuses to load.
https://efforg.github.io/congress-forms-test/

Manually forcing http circumvents this, but I propose switching all content to SSL.

**Comment by konklone** [comment]
Seems easy enough. I'll change a few URLs to be protocol-relative.

**Comment by konklone** [comment]
Closing this in favor of the open PR at #28. Thanks for the nudge!
